apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tmlsssodevaks01-958d"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tmlsssodevaks01-958d"
  template:
    metadata:
      labels:
        app: "tmlsssodevaks01-958d"
    spec:
      containers:
        - name: "tmlsssodevaks01-958d"
          image: "tmlsssvdevcr01.azurecr.io/tmlsssodevaks01"
          ports:
          - containerPort: 80