apiVersion: v1
kind: Service
metadata:
    name: "tmlsapidevaks01-a066"
    labels:
        app: "tmlsapidevaks01-a066"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "tmlsapidevaks01-a066"