apiVersion: v1
kind: Service
metadata:
    name: "tmlsssodevaks01-958d"
    labels:
        app: "tmlsssodevaks01-958d"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "tmlsssodevaks01-958d"