on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: tmlsssvdevcr01.azurecr.io
        username: ${{ secrets.acr_tmlsssvdevcr01_username }}
        password: ${{ secrets.acr_tmlsssvdevcr01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t tmlsssvdevcr01.azurecr.io/tmlsapidevaks01:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push tmlsssvdevcr01.azurecr.io/tmlsapidevaks01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_tmlsapidevaks01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep tmls-api-dev-aks018eec | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace tmls-api-dev-aks018eec`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: tmls-api-dev-aks018eec
        container-registry-url: tmlsssvdevcr01.azurecr.io
        container-registry-username: ${{ secrets.acr_tmlsssvdevcr01_username }}
        container-registry-password: ${{ secrets.acr_tmlsssvdevcr01_password }}
        secret-name: tmlsapidevakdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: tmls-api-dev-aks018eec
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          tmlsssvdevcr01.azurecr.io/tmlsapidevaks01:${{ github.sha }}
        imagepullsecrets: |
          tmlsapidevakdockerauth
